import type { Metadata } from 'next';
import { Head, Html, Main, NextScript } from 'next/document';

// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Document({ children }: { children: React.ReactNode }) {
  return (
    <Html lang='en'>
      <Head>
        {/* <meta name='twitter:image' content='<generated>' />
        <meta name='twitter:image:type' content='<generated>' />
        <meta name='twitter:image:width' content='<generated>' />
        <meta name='twitter:image:height' content='<generated>' /> */}
      </Head>
      <body // className={inter.className}
        dir='rtl'
        id='root'
      >
        <Main />
        <NextScript />
        {children}
      </body>
    </Html>
  );
}
